### ISSUE TITLE
Values could be to big for INT

### ISSUE THREAD

**Issue by marcelfischer** [justintime/nagios-plugins#21]
We have systems with more than 2TB RAM.
If free or used memory is too big for an integer, this fails:
\# Round to the nearest KB
$free_memory_kb = sprintf('%d',$free_memory_kb);
$used_memory_kb = sprintf('%d',$used_memory_kb);
$caches_kb = sprintf('%d',$caches_kb);

I changed it to:
\# Round to the nearest KB
$free_memory_kb = sprintf('%.0f',$free_memory_kb);
$used_memory_kb = sprintf('%.0f',$used_memory_kb);
$caches_kb = sprintf('%.0f',$caches_kb);

**Comment by justintime** [comment]
Just added your fix to master, thanks @marcelfischer !
